### PR TITLE
typo: globabl -> global

### PR DESCRIPTION
**Pull request by CompRhys**
Fix simple typo

### CODE REVIEW

**Comment by CompRhys** [comment]
"Reminder that it looks like <blank>"

due to parsing error for 
```
\begin{eqnarray*}
h_{n,k} =& \bar{a}_{n,k} h_{k-1} + \bar{b}_{n,k} x_k  \\
y_k =& \sum_n c_{n, k} h_{n, k}   
\end{eqnarray*}
```

Indeed many equations are actually not being displayed due to this error but this was the first that really broke the flow

**Comment by srush** [comment]
Thanks!

**Comment by srush** [comment]
Oh man, I can't believe the math wasn't there. Fixed now.

**Comment by CompRhys** [comment]
don't worry even without the math it was a great aid! I made it more than halfway through before I was like 'mhmm this sentence is missing something'

**Pull request merged**
